### ISSUE TITLE
About feature of this great program: just few steps forward are needed !

### ISSUE THREAD

**Issue by Nokia808** [flathub/net.sourceforge.jpdftweak.jPdfTweak#1]
Hi dear. 
1st of all I would to say thank you for making this great program available for Linux users as flatpak package ....
2md I would like to congratulate you for success in merging your PR here ....

Dear, this program unfortunately his developer kill it by refuse to add new features to it. And as you know last stable release for this program is dated to 2011 ! From my previous contact with developer, I know that there is newer version but he did not release it !! Also, I asked him to add few new features (or in fact just enhancements) for already existing features but he said: I'm stop from adding new features to it .... The developer ready to receive new features from other peoples who push them as PR to this program ...... Unfortunately, no one interested in further development for this program & most of those I asked answer me: "because this is a java program ......."

So, I would asking you: do you think to add new features to this program to make it complete ?

In fact all what needed are:
1) making user able to determine watermark to be added on:
- odd pages
- even pages
- specific page(s)
Currently, watermark applied on all pages of PDF & this not suitable for many users.
2) make program able to save to same input file: currently, output file should not be same of input file: this mean that currently new changes "saved as" new file meaning that every trail to edit something we need to create new PDF.
3) encryption is only 128 bit. We need to support 256 bit encryption also.
4) regarding cropping: currently no manual cropping allowed. Program need custom cropping that allow user to determine manually measures of up, down, left, right margins that should be cropped....
5) currently, we have only "empty before" option to add new empty page(s). This prevent user from add new empty page(s) at the very end of PDF (after last page of PDF). So, we need new option: "empty after" corresponding to the current "empty before" option.
6) outlines creating need few tweaks to make this process easier .... For example we need to make every newly created outline take the same depth of the just above it outline so as to make it easier to create branched tree of outlines. Also, we need to make every newly created outline at a specific value which is the most commonly used [I forget it because I leave this program since long time due stop of it's developing] ........
7) in edit document info program need new features to: make creating date empty, make modification date empty.

Just by adding these new features (or in fact just enhancements) we will have almost complete program ..... I can not understand why developer of this program kill it ??!!!

Can you add these few tweaks ? The developer will accept PR from you ......

**Comment by bilelmoussaoui** [comment]
This is completely unrelated to the Flatpak package.

**Comment by Nokia808** [comment]
@bilelmoussaoui 
Hi dear. I liked from this issue JUST & ONLY JUST to contact with @felipehw 
I searched for an email to contact it but I did not find .....

Just I like to contact it about this, no more ..... Can you help me for that ?

**Comment by Nokia808** [comment]
@bilelmoussaoui 
@felipehw 
This is my email for forums & public sites discussion:
yousifjkadom@yahoo.com
Kindly if @felipehw  contact me on this email to discuss this issue in private ......

Thank you.

**Comment by felipehw** [comment]
Hi @Nokia808,
I talked with the developer and he allows me to release a 1:1 version here.
I know that is an awesome software and, sadly, the original developer has stopped its development.
But I'm not a Java developer :(. I expect that a bigger publicization of this software in Flathub will call the attention of others developers to this code.
That said, any improvement to this software will probabily be a fork of the original and so ... will need another package at Flathub.

**Comment by Nokia808** [comment]
@felipehw 
Thank you too much for response. There is no problem in creating new flatpak package. The problem is that no one accept to fork it just for being a Java !! It is not a security or anonymity program to be afraid from Java ! Moreover, a very strong security & privacy & anonymity application are Jave. Most dramatic example is i2p project ......

I will try to contact developer asking to pay for him to add the enhancement but I'm nearly sure he will refuse ......
